spring:
  jpa:
    show-sql: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
      springframework:
        security: debug
auth:
  jwt:
    issuer: "project.todolist.com"
    secretKey: "kJ63Qe7E6zqQ2fOQ2z9dNiTsP1_bBnIF"
    tokenExpiration: 168

oauth2:
  kakao:
    client_id: "46b2bea914ad0bd9ccb080d5c6aa640b"
    redirect_url: "http://localhost:8080/oauth2/callback/kakao"
    auth_server_base_url: "https://kauth.kakao.com"
    resource_server_base_url: "https://kapi.kakao.com"
